export const LOCATIONS_REFERENCE_DATA_SUCCESS = 'LOCATIONS_REFERENCE_DATA_SUCCESS';
export const TEAMS_REFERENCE_DATA_SUCCESS = 'TEAMS_REFERENCE_DATA_SUCCESS';
export const COACHES_REFERENCE_DATA_SUCCESS = 'COACHES_REFERENCE_DATA_SUCCESS';
export const PLAYERS_REFERENCE_DATA_SUCCESS = 'PLAYERS_REFERENCE_DATA_SUCCESS';
export const TEAM_STAFF_REFERENCE_DATA_SUCCESS = 'TEAM_STAFF_REFERENCE_DATA_SUCCESS';
export const TEAM_PLAYERS_REFERENCE_DATA_SUCCESS = 'TEAM_PLAYERS_REFERENCE_DATA_SUCCESS';
